---
- name: reload systemd
  become: yes
  become_method: sudo
  command: systemctl daemon-reload

- name: apt-get clean
  become: yes
  become_method: sudo
  apt:
    autoclean: yes

- name: apt-get autoremove
  become: yes
  become_method: sudo
  apt:
    autoremove: yes

# https://github.com/ansible/ansible/issues/22171
- name: restart auditd
  become: yes
  become_method: sudo
  command: service auditd restart

- name: generate auditd
  become: yes
  become_method: sudo
  command: augenrules

...
