---
- name: gather facts
  setup:
  become: no
  tags: always

- name: Set OS family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags: always

- name: Set OS dependent variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  tags: always

- include_tasks: pkgupdate.yml
  tags: pkgupdate

- include_tasks: firewall.yml
  tags: firewall

- include_tasks: limits.yml
  tags: limits

- include_tasks: systemd.yml
  tags: systemd

- include_tasks: login_defs.yml
  tags: login_defs

- include_tasks: adduser.yml
  tags: adduser

- include_tasks: minimize_access.yml
  tags: minimize_access

- include_tasks: modprobe.yml
  tags: modprobe

- include_tasks: pam.yml
  tags: pam

- include_tasks: profile.yml
  tags: profile

- include_tasks: securetty.yml
  tags: securetty

- include_tasks: suid_sgid.yml
  when: os_security_suid_sgid_enforce
  tags: suid_sgid

- include_tasks: sysctl.yml
  tags: sysctl

- include_tasks: user_accounts.yml
  tags: user_accounts

- include_tasks: hosts.yml
  tags: hosts

- include_tasks: rhosts.yml
  tags: rhosts

- include_tasks: logrotate.yml
  tags: logrotate

- include_tasks: yum.yml
  when: ansible_os_family == 'RedHat'
  tags: yum

- include_tasks: apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: apt
...
